name: PowerShell Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        run: Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run Linter
        run: Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning,Error
        shell: pwsh
